### ISSUE TITLE
EstDim() error

### ISSUE THREAD

**Issue by merlevede** [jinghan1018/tensorICA#1]
Hello,

I am trying your method on a dataset with 3 layers: CNA, methylation and RNASeq data.

I kept genes that have at least some variance across each layer and genes that were common in these 3 layers. Thus, 4560 genes remain.

The data of each data type are stored in a dataframe. Then, I use an array:
>my_dataset <- array(c(as.matrix(CNA),as.matrix(hm27),as.matrix(RNASeq)),dim = c(nrow(CNA),ncol(CNA),3))

To have the same format as in your example, I tried also:
>my_dataset <- array(c(as.matrix(CNA),as.matrix(hm27),as.matrix(RNASeq)),dim = c(3,ncol(CNA),nrow(CNA)))

In both cases, I get the following error message:
>Dim.l <- EstDim(my_dataset)
>Error in while (step == 0) { : 
  valeur manquante là où TRUE / FALSE est requis

which means: missing value where TRUE/FALSE is required.

I guess I have a problem in my input data, but I cannot figure it out.
I would appreciate your help.
Jane

**Comment by jinghan1018** [comment]
I see. Probably you need to put your data type index in the first mode of the input array. 
The correct input format of EstDim should be array[datatype,sample,features].
You can try to make a list of all your input matrices and then use the following function:

buildTensor3R <- function(m.l){
  nT <- length(m.l)
  nG <- nrow(m.l[[1]])
  nS <- ncol(m.l[[1]])
  out <- array(dim=c(nT,nS,nG))
  for(s in 1:nS){
    for(t in 1:nT){
      out[t,s,] <- m.l[[t]][,s]
    }
  }
  names(out) <- c("Types","Samples","Genes")
  return(out)
}
Hope it helps.

**Comment by merlevede** [comment]
Thank you a lot Han for your response.
I tried the following as you suggested:
>my_dataset=list("CNA"=as.matrix(CNA), "hm27"=as.matrix(hm27), "mRNA"=as.matrix(RNASeq))
>buildTensor3R <- function(m.l){
  nT <- length(m.l)
  nG <- nrow(m.l[[1]])
  nS <- ncol(m.l[[1]])
  out <- array(dim=c(nT,nS,nG))
  for(s in 1:nS){
    for(t in 1:nT){
      out[t,s,] <- m.l[[t]][,s]
    }
  }
  names(out) <- c("Types","Samples","Genes")
  return(out)
}
>Dim.l <- EstDim(buildTensor3R(my_dataset))

But I still have the same error message: 
> Dim.l <- EstDim(buildTensor3R(my_dataset))
Error in while (step == 0) { : 
  valeur manquante là où TRUE / FALSE est requis

Here is the info about my tensor:
> str(buildTensor3R(my_dataset))
 num [1:3, 1:11, 1:4560] 2 0.0265 0.4926 2 0.039 ...
  attr(*, "names")= chr [1:150480] "Types" "Samples" "Genes" NA ...

Do you have any idea about what is wrong in my input?

**Comment by jinghan1018** [comment]
I checked the code. The error comes from the fucntion EstDimRMT, which is the main function to run RMT. So it is likely that  your data tensor has a problem. Is there any possible it contains NA value?

**Comment by merlevede** [comment]
Thank you for your answer.
There is no NA value in each of the dataframes: CNA, hm27 and RNASeq...

**Comment by merlevede** [comment]
After some emails exchanged with Han, the solution was to check the row variance of the different layers. If others are interested, it should be different from 0

**Comment by jinghan1018** [comment]
> Dear @jinghan1018,
> 
> I tried to install your package tensorICA by following instructions from this page: https://aeteschendorff-lab.github.io/software/tensorICA/ but unfortunately an error occur:
> Failed to install 'tensorICA' from GitHub
> Does any other ways of installation exist?
> Thank you very much in advance!
> 
> Best regards,
> Polina

Dear Polina,

How about downloading the source code and install the package locally? It works fine on my PC.

Best,
Han
